apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- objects.yaml

patches:
- target:
    kind: ConfigMap
    name: car
  patch: |-
    - op: add
      path: /data/bodyStyle
      value: coupe

buildMetadata:
- originAnnotations
