name: Continuous Integration
on:
  # See https://docs.github.com/en/actions/reference/events-that-trigger-workflows.
  push:
    branches:
    - main
    tags:
    - v*
  pull_request:
jobs:
  bazel-source-inspection:
    runs-on: ubuntu-latest
    steps:
    - name: Check out VCS repository
      uses: actions/checkout@v2
    - name: Confirm Bazel files is formatted per "buildifier"
      uses: thompsonja/bazel-buildifier@v0.3.0
      with:
        # See https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md.
        warnings: -function-docstring,-module-docstring
  build-test:
    runs-on: ubuntu-latest
    steps:
    - name: Cache bazel-related artifacts
      uses: actions/cache@v2
      env:
        cache-name: bazel-cache
      with:
        path: |
          ~/.cache/bazelisk
          ~/.cache/bazel
        key: ${{ runner.os }}-${{ env.cache-name }}
    - name: Check out VCS repository
      uses: actions/checkout@v2
    - name: Install FUSE
      run: sudo apt install libfuse2
    - name: Install sandboxfs
      run: |
        f='./sandboxfs.tar.gz'
        curl --location --output "${f}" --silent \
          https://github.com/bazelbuild/sandboxfs/releases/download/sandboxfs-0.2.0/sandboxfs-0.2.0-20200420-linux-x86_64.tgz
        sudo tar xzv -C /usr/local -f "${f}"
        rm "${f}"
    - name: Build all Bazel targets
      run: |
        bazel build --experimental_use_sandboxfs //...
    - name: Test all Bazel targets
      # Work around https://github.com/bazelbuild/bazel/issues/7470 by
      # way of the suggestion here:
      # https://github.com/bazelbuild/bazel/issues/7470#issuecomment-764591831.
      run: |
        bazel test \
          --experimental_use_sandboxfs \
          --strategy TestRunner=processwrapper-sandbox \
          --test_output=errors \
          //...
